### ISSUE TITLE
map.js code review #1 : makeClickEvent Method

### ISSUE THREAD

**Issue by ihatelua** [jungu0416/TRAVEL_PROJECT#1]
https://github.com/jungu0416/Travel/blob/969ddb739bf98fd03cfdd66b61a3e54e357daf6a/public/map.js#L4-L10

:nauseated_face::nauseated_face::nauseated_face:
  
<br>  

```javascript
makeClickEvent(travelArr) {
    travelArr.forEach(e => 
        e.addEventListener('click', () => this.fillArea(travelArr[i]))) 
}
```
I think it would be good to refactoring with the above code! 

:relaxed::relaxed::relaxed:

**Comment by jungu0416** [comment]
Array-Like Objects can't apply forEach statement. thx for the review by the way

**Comment by jungu0416** [comment]
Array-Like Objects can't apply forEach statement. thx for the review by the way
